### ISSUE TITLE
delta -v does not return version

### ISSUE THREAD

**Issue by cornelisonc** [DeltaSystems/delta-cli-tools#2]
Per the help script, 

`  -V, --version         Display this application version`

However, running `delta -V` returns only the name of the project, not the version of the delta-cli application. Is this working as intended? May need to either update the helptext or the response.

**Comment by griffbrad** [comment]
Apparently that is a flag added by Symfony automatically.  Adjusted to automatically grab the version from Composer when possible.  In 1.17.2.
